[tool.mypy]
strict = true
exclude = "(venv|core)"
follow_imports = "skip"
disallow_untyped_decorators = false
implicit_reexport = true # don't require us to explicitly write name of every requirement class

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "major",
]
