name: Degree validator checks

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "degree-validator/**"
    paths-ignore:
      - "**/README.md"

defaults:
  run:
    working-directory: degree-validator

jobs:
  run-tests:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run pytest --verbose

      - name: Run type checker
        run: |
          mypy .

  run-type-checks:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Run type checker
        run: |
          pipenv run mypy .
