name: Build

on:
  push:
    paths:
      - "degree-validator/**"
  pull_request:
    paths:
      - "degree-validator/**"

defaults:
  run:
    working-directory: degree-validator

jobs:
  release:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run tests
        run: |
          pytest --verbose

      - name: Run type checker
        run: |
          mypy .
